# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"U\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x10\n\x06\x61uthor\x18\x03 \x01(\t:\x00\x12\r\n\x05genre\x18\x04 \x03(\t\x12\x0f\n\x04year\x18\x05 \x01(\x05:\x01\x30\"j\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x02(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12 \n\x06status\x18\x03 \x02(\x0e\x32\x10.InventoryStatusB\x07\n\x05media\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\"#\n\x12\x43reateBookResponse\x12\r\n\x03msg\x18\x02 \x01(\t:\x00*+\n\x0fInventoryStatus\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32\x63\n\x10InventoryService\x12*\n\nCreateBook\x12\x05.Book\x1a\x13.CreateBookResponse\"\x00\x12#\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x05.Book\"\x00\x42\x1f\x42\x15InventoryServiceProtoP\x01\xa2\x02\x03RTG')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\025InventoryServiceProtoP\001\242\002\003RTG'
  _INVENTORYSTATUS._serialized_start=283
  _INVENTORYSTATUS._serialized_end=326
  _BOOK._serialized_start=19
  _BOOK._serialized_end=104
  _INVENTORYITEM._serialized_start=106
  _INVENTORYITEM._serialized_end=212
  _GETBOOKREQUEST._serialized_start=214
  _GETBOOKREQUEST._serialized_end=244
  _CREATEBOOKRESPONSE._serialized_start=246
  _CREATEBOOKRESPONSE._serialized_end=281
  _INVENTORYSERVICE._serialized_start=328
  _INVENTORYSERVICE._serialized_end=427
# @@protoc_insertion_point(module_scope)
